version: 2
jobs:
  build:

    working_directory: ~/entelect-challenge

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          key: entelect-challenge-{{ checksum "pom.xml" }}

      - run: mvn package dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: entelect-challenge-{{ checksum "pom.xml" }}

      - run: mvn clean package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: runtime/target/runtime-1.0-SNAPSHOT-jar-with-dependencies.jar
